name: publish

on:
  push:
    tags:
      - "v*"
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - run: npm i -g corepack && corepack enable
      - uses: actions/setup-node@v6
        with:
          cache: "pnpm"
          node-version: "24"
          package-manager-cache: false
      - run: pnpm install --frozen-lockfile
      - run: pnpm typecheck
      - run: pnpm build
      - run: pnpm vitest
      - run: npm publish --provenance --no-git-checks --access public
